# ===============================
# CONEXIÓN A POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/sneakerstore
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
# "update" le dice a Spring que cree o actualice las tablas automáticamente basado en nuestro código Java
spring.jpa.hibernate.ddl-auto=update

# Estas dos líneas son oro puro para un desarrollador: te mostrarán en consola el SQL exacto que Spring está ejecutando
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURACIÓN DE FLYWAY
# ===============================
# Lo apagamos temporalmente mientras diseñamos nuestras primeras entidades. Lo encenderemos cuando pasemos a producción.
spring.flyway.enabled=false

# ===============================
# CONFIGURACIÓN DE SUBIDA DE ARCHIVOS
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
